spring.application.name=spring-kafka

# ============================
# PostgreSQL Yap?land?rmas?
# ============================

spring.datasource.url=jdbc:postgresql://localhost:5432/kafka_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# Entity de?i?ikliklerine göre tablolar? günceller
spring.jpa.hibernate.ddl-auto=update

# Hibernate taraf?ndan çal??t?r?lan SQL sorgular?n? gösterir
spring.jpa.show-sql=true

# SQL sorgular?n? daha okunabilir biçimde gösterir
spring.jpa.properties.hibernate.format_sql=true


# ============================
# Kafka Ba?lant?s?
# ============================

spring.kafka.bootstrap-servers=localhost:9092


# ============================
# Producer Yap?land?rmas?
# ============================

# Mesaj anahtar?n? (Key) String -> byte[] format?na çevirir
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Outbox payload zaten JSON String oldu?u için StringSerializer kullan?yoruz
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Producer retry durumlar?nda ayn? mesaj?n Kafka'ya iki kez yaz?lmas?n? engellemeye yard?mc? olur
spring.kafka.producer.properties.enable.idempotence=true

# Mesaj?n gerekli replikalar taraf?ndan onaylanmas?n? bekler
spring.kafka.producer.acks=all


# ============================
# Consumer Yap?land?rmas?
# ============================

# Consumer'?n dahil oldu?u Consumer Group
spring.kafka.consumer.group-id=order-group

# Geçerli commit edilmi? offset yoksa mevcut en eski mesajdan okumaya ba?lar
spring.kafka.consumer.auto-offset-reset=earliest

# Mesaj anahtar?n? byte[] -> String format?na çevirir
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka'dan gelen JSON verisini Java nesnesine çevirir
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# JSON deserialization s?ras?nda güvenilen Java paketleri
spring.kafka.consumer.properties.spring.json.trusted.packages=org.oskay.springkafka.event

# Gelen JSON'un varsay?lan olarak hangi Java s?n?f?na dönü?türülece?ini belirtir
spring.kafka.consumer.properties.spring.json.value.default.type=org.oskay.springkafka.event.OrderCreatedEvent